env:
  es6: true
  node: true
  mocha: true
extends: airbnb-base
parserOptions:
  sourceType: module
rules:
  arrow-body-style: 0
  class-methods-use-this: 0
overrides:
  - files:
      - "*.spec.js"
    rules:
      no-unused-expressions: off
