language: node_js

node_js:
  - 10.15.3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script: 
    - npm build
    - npm run test-unit-with-coverage

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - node_modules

after_success:
  - make build

deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
skip_cleanup: true