language: node_js

node_js:
  - 10.15.3

script: 
    - npm build
    - npm run test-unit-with-coverage

cache:
  directories:
    - node_modules

after_success:
  - make build

deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
skip_cleanup: true